[profile]
name = "utilities"
description = "Shared system utilities"
includes = []
required_packages = []
optional_packages = []

[platforms.linux]
required_packages = ["qdirstat", "baobab", "kate", "konsole", "fastfetch", "dolphin", "mission-center"]
optional_packages = []